### ISSUE TITLE
[Powerslave/Exhumed] [1.1.2] Using heart item causes graphical error

### ISSUE THREAD

**Issue by srludicolo** [ZDoom/Raze#415] opened 2021-05-29 00:43 UTC
Happened in level 2- using the heart item causes a glitch where a sprite covers the center of the screen, and makes the game virtually unplayable. 

![Exhumed_0000](https://user-images.githubusercontent.com/83472414/120052786-a1a40480-bfec-11eb-82b7-25e40ddef142.png)

**Comment by coelckers** [comment] 2021-05-29 09:53
You are not the first person to report corruption when using the heart, but I can't reproduce it myself.
Did you by any chance autoload any graphics mods for one of the other games?

**Comment by sinisterseed** [comment] 2021-05-29 10:23
It shouldn't be mod related, but I have no idea what causes this random stupidity.

I used to be able to trigger it randomly in vanilla, but nothing as of late. It seemed to be more common when continuing a game from a save as opposed to starting fresh.

**Comment by coelckers** [comment] 2021-05-29 11:05
It's probably one of the animation sequences being fucked up. That entire code is an atrocity of bad sprite offsets being compensated by animations that have the screen offset baked in. 
If it wasn't for potential mod compatibility I would have torn it all apart and built proper animations out of the sprites that can be used in a sane fashion.

**Comment by Gaerzi** [comment] 2021-05-29 12:40
How many Exhumed mods actually exist? Might be worth doing that anyway.

**Comment by sinisterseed** [comment] 2021-05-29 13:08
Not many, that's for sure. And from what I've seen, they're all just maps.

**Comment by srludicolo** [comment] 2021-05-29 20:02
@coelckers I can attach a save file. 
[save0000.zip](https://github.com/coelckers/Raze/files/6565270/save0000.zip)

**Comment by coelckers** [comment] 2021-06-01 09:36
See also https://forum.zdoom.org/viewtopic.php?f=340&t=72072

**Comment by Dzierzan** [comment] 2021-06-06 10:33
@Gaerzi 

Well.... zero? There's only one custom map pack with 3 levels. Voxel pack which only replaces some sprites with voxels. Skybox addon which just updates skyboxes and a small mini addon which replaces M60 sprites.

@coelckers 

Powerslave/Exhumed is not really good for modding and its low popularity never spawned serious mods, You should go ahead and torn that apart and then built proper animations out of the sprites.

**Comment by sinisterseed** [comment] 2021-06-06 10:52
That's... very interesting. That's actually all there ever was made for PS/Exhumed?

That would be good news since it means this can be reworked in a sane fashion without risking to break mods at all (since there's almost... nothing to break to begin with).

**Comment by Dzierzan** [comment] 2021-06-06 11:00
Yeah, and there's also upscale pack for that too, but again, this is just a visual enhancement. So @coelckers should go again and rewrite that if that helps. Nothing will be lost.

**Comment by coelckers** [comment] 2022-10-01 11:53
Closing because I have never been able to reproduce this.

**Comment by michaelneverwins** [comment] 2023-02-12 22:50
I see that this is closed, but just in case it helps, here's another save file.

[save0000.zip](https://github.com/ZDoom/Raze/files/10717498/save0000.zip)

The glitch happened right after I quick-saved, so I closed Raze to make a copy of the save file. Opening Raze back up to confirm that it happens consistently, I'm now seeing that the glitch is there as soon as I load my save from the main menu:
![2023-02-12_17-42-19](https://user-images.githubusercontent.com/73746653/218341742-7eb99d6b-fec4-4ef5-b94b-486222bdddb7.png)
Loading the save again from there, it's gone:
![2023-02-12_17-42-44](https://user-images.githubusercontent.com/73746653/218341750-d1577a60-86af-407e-a2c8-9bd8735f9b6a.png)
Using the heart makes it appear again:
![2023-02-12_17-42-48](https://user-images.githubusercontent.com/73746653/218341760-2c27d8df-f08f-4901-b8cc-ad3bf9b10a30.png)
Taking a quick bath in the lava to hurt myself and then using the heart *again* makes this happen:
![2023-02-12_17-43-02](https://user-images.githubusercontent.com/73746653/218341790-498266b9-6530-4eda-aac7-08b394267c51.png)
Should I even be able to use the heart more than once or is that part of the glitch? In any case, I've done this a few times so it's happening consistently at least for me. I'm using Raze 1.6.2 on Linux Mint 20.3.

**Comment by michaelneverwins** [comment] 2023-02-12 23:34
Unzipping my save file and searching `session.json` for relevant text, I found the following:
```json
"items":[250,2,2,2,1,1,0,0]
```
Note that, in that save, I have 2 scarabs, 2 torches, 2 hands, 1 eye, and 1 mask — in addition to the glitchy heart, which I suppose should also be showing 1 to 5 of those little squares lit up, unless the heart isn't supposed to work that way.

So I changed the `250` to `3`, zipped it back up, and loaded the modified save. The glitch no longer occurs. It still seems to be using the heart automatically for some reason when I load from the main menu, leaving the item counter at 2, but then I load again and it shows 3.

**Comment by michaelneverwins** [comment] 2023-02-13 04:09
After writing the comment above, it occurred to me that I had used the heart item several times in that level prior to encountering this glitch — perhaps, say, about half a dozen times (while wondering why I wasn't running out of hearts), but I wasn't counting — and 250 is pretty close to a power of two — off by half a dozen, in fact — as if the counter for this item had been corrupted by some kind of overflow bug. Meanwhile, as I noted in my testing of the graphical glitch, the game seemed to be using the heart when I loaded my save from the main menu immediately after starting Raze. So I got an idea for reproducing the glitch from scratch, and it works. The following was done after renaming my `raze.ini` file and letting Raze create a fresh one, to ensure I was using the default configuration.

1. Started Raze and selected *Exhumed*.
2. Opened the console and entered `map lev5` to go to the fifth level. (There's a heart on the left across some water.)
3. Jumped into the water, let the fish bite, and got the heart.
4. Saved the game, with a heart in the inventory and less than full health. ([save0000.zip](https://github.com/ZDoom/Raze/files/10718389/save0000.zip))
5. Exited out of Raze, started Raze again, and selected *Exhumed*.
6. From the main menu, loaded the save created in step 4. This caused the heart to be used up, filling my health, despite the fact that I hadn't picked up any magic.
7. Jumped into the water and let the fish bite some more.
8. Saved the game, now with less than full health and the heart used up. ([save0001.zip](https://github.com/ZDoom/Raze/files/10718398/save0001.zip))
9. Exited out of Raze, started Raze again, and selected *Exhumed*.
10. From the main menu, loaded the save created in step 8. This caused my health to be filled up again, and the heart was back in my inventory.
11. Saved the game, with a mysterious heart item that shouldn't exist. ([save0002.zip](https://github.com/ZDoom/Raze/files/10718419/save0002.zip))

If you unzip that third save and open `session.json`, you will see
```
"items":[255,0,0,0,0,0,0,0]
```
where the number of hearts which should be `0` has rolled over to `255`.

At this point, I jumped into the water so the fish kept biting, and repeatedly
* saved the game,
* exited Raze,
* started Raze, and
* loaded my save from the main menu.

After doing this enough times, the glitch appeared: [save0003.zip](https://github.com/ZDoom/Raze/files/10718442/save0003.zip)

The weird sprites start showing up on the screen when the heart item's counter reaches 249, and I believe the root cause is that the game erroneously uses a heart when loading, from the main menu immediately after starting Raze, a save in which the player has less than full health.

I tested this on `lev5` because the heart is right there at the beginning, and I figured that I needed to obtain the heart and have it selected in order to initiate this bug. However, further testing indicates that this isn't necessary.

I started a *new game*, ran to the first enemies, took damage, saved the game ([save0004.zip](https://github.com/ZDoom/Raze/files/10718485/save0004.zip)), exited Raze, opened Raze, loaded the save, and saved again ([save0005.zip](https://github.com/ZDoom/Raze/files/10718490/save0005.zip)). In this last save, I now have a heart selected in the inventory, and it shouldn't exist. Unzipping this last save's `session.json`, I see the `255` again. So it seems that opening Raze and immediately loading any save which has less than full health and no hearts will result in a glitched heart that will start causing graphics glitches after about half a dozen uses.

**Closed** 2023-03-16 02:06 UTC
Labels: bug
