### ISSUE TITLE
[BUG] Center bridge segment on E2L5 collapses

### ISSUE THREAD

**Issue by Talon1024** [ZDoom/Raze#781] opened 2022-12-12 16:32 UTC
### Raze version

1.6.0

### Which game are you running with Raze?

Duke Nukem 3D

### What Operating System are you using?

Linux x86_64

### Please describe your specific OS version

Kubuntu 20.04 LTS

### Relevant hardware info

Intel i5-4690K CPU, NVidia GeForce GTX 970 GPU

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

After you press the switch to lower the bridge at the end of E2L5, the center segment of the bridge at the end of E2L5 will "collapse". It will snap to below the floor and start slowly rising up as soon as you step on it.

[Here's a saved game](https://github.com/ZDoom/Raze/files/10210077/save0001.zip).

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Load the saved game
2. Press the switch to lower the bridge
3. Step onto the segment which is in the middle when the bridge is raised
4. That segment will instantly fall below the floor and start slowly rising up

**Comment by coelckers** [comment] 2022-12-13 12:48
should be fixed with 4f388c3589292bb7305760770eef623d6c22b8c6

At least I couldn't reproduce it anymore, but this is such a house-of-cards setup that there might still be some surprises.

**Closed by coelckers** 2022-12-13 12:48 UTC
Labels: bug
