### ISSUE TITLE
[BUG] Crash on Launch on Linux, Memory Leak

### ISSUE THREAD

**Issue by d10sfan** [ZDoom/Raze#986] opened 2023-08-21 01:12 UTC
### Raze version

1.7.1

### Which game are you running with Raze?

Blood

### What Operating System are you using?

Linux x86_64

### Please describe your specific OS version

Endeavor OS

### Relevant hardware info

AMD 6700 XT

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

When attempting to load Blood, or Shadow Warrior, or NAM, Raze will create a window for a short time, but it's frozen and has no output of its own meaning that there's no output, just seeing whatever is already on my screen but frozen, unless I alt+tab, and then crash. So it seems like there's a window being created but there's nothing being drawn in it before the game crashes.

When I run raze in a Terminal window, it takes the terminal window with it. This is without any configuration, just attempting to launch the game. I tried running with gdb but the terminal crashes when the game does, so I'm unable to do anything.

After looking at journalctl and watching the system monitor, it looks like the problem is raze is trying to use up all available memory on my system. It mentions kconsole in the below log because that's the terminal I used to launch raze, but raze itself was using 23 GB (I have 32 gb of ram) of memory before it was shut down, from looking at the activity monitor.

```
Aug 20 20:09:20 d10sfan-desktop systemd[1]: user@1000.service: A process of this unit has been killed by the OOM killer.
Aug 20 20:09:20 d10sfan-desktop systemd[1160]: app-org.kde.konsole-539149770b4a418eb442146415418523.scope: A process of this unit has been killed by the OOM killer.
Aug 20 20:09:20 d10sfan-desktop systemd[1160]: app-org.kde.konsole-539149770b4a418eb442146415418523.scope: Failed with result 'oom-kill'.
Aug 20 20:09:20 d10sfan-desktop systemd[1160]: app-org.kde.konsole-539149770b4a418eb442146415418523.scope: Consumed 11.726s CPU time.
```

**This issue is not in the 1.6.2 release, but is in the 1.7.0 release, so something occurred between those two releases to cause this to happen** 

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Download Raze 1.7.1 Linux portable from https://github.com/ZDoom/Raze/releases/tag/1.7.1
2. Attempt to run raze with `./raze`
3. Stuck window gets created, then a few seconds later, game crashes because it's attempting to use up all available memory.

### Your configuration

```ini
No configuration, running it from scratch (deleted ~/.config/raze for testing).
```

### Provide a Log

[crash.log](https://github.com/ZDoom/Raze/files/12390073/crash.log)

Message from journalctl, showing that raze was killed due to attempting to use all available memory.
```
Aug 20 20:09:20  d10sfan-desktop systemd[1]: user@1000.service: A process of this unit has been killed by the OOM killer.
Aug 20 20:09:20 d10sfan-desktop systemd[1160]: app-org.kde.konsole-539149770b4a418eb442146415418523.scope: A process of this unit has been killed by the OOM killer.
Aug 20 20:09:20 d10sfan-desktop systemd[1160]: app-org.kde.konsole-539149770b4a418eb442146415418523.scope: Failed with result 'oom-kill'.
```

**Comment by mjr4077au** [comment] 2023-09-24 04:58
Duplicate of #966.

**Closed by mjr4077au** 2023-09-24 04:58 UTC
Labels: bug, OS-specific
