### ISSUE TITLE
[BUG] Giant sprite shadows

### ISSUE THREAD

**Issue by Talon1024** [ZDoom/Raze#884] opened 2023-02-09 20:56 UTC
### Raze version

Raze 1.7pre-564-g 17392fe400

### Which game are you running with Raze?

Shadow Warrior

### What Operating System are you using?

Linux x86_64

### Please describe your specific OS version

Kubuntu 22.04 LTS

### Relevant hardware info

Intel i5-4690K CPU, NVidia GeForce GTX 970 GPU

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Enemies beneath the ground cast gigantic sprite shadows. It seems like the further beneath the ground an enemy is, the bigger the shadow is. I'm not sure if this happened in the OG or not, but it doesn't look right either way.

[Here's a saved game](https://github.com/ZDoom/Raze/files/10701423/growing.shadow.zip) for Shadow Warrior: Wanton Destruction

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Kill an enemy so that their corpse lies on a lift
2. Use the lift
3. Notice the giant shadow cast by the corpse

**Comment by mjr4077au** [comment] 2023-03-14 09:39
There's a few things going on here. The commit 3271c2011ee97291312fd88a36ac7a338b23bf44 was meant to fix an issue where the sprite's shadow wasn't drawing on a moving sector. It does fix that at the expense of causing the issue you've reported.

The _actual_ issue is dead actors don't move after dying, and on moving sectors they just sort of stay where they are:

https://user-images.githubusercontent.com/48643140/224959454-a1035967-9f21-48b9-b9b7-1a993fa206e0.mp4

When I last checked on how best to fix this, it looked like the game would have needed some fundamental changes to how it processes actors in the ticker. I'll leave it here for now, but probably won't be fixed overnight.

**Comment by mjr4077au** [comment] 2023-03-14 20:46
Actually, closing this one as it's a duplicate of https://github.com/ZDoom/Raze/issues/847

**Closed** 2023-03-16 00:23 UTC
Labels: bug
