### ISSUE TITLE
[BUG]: Duke: RPG has no projectile sound when firing, only impact of the projectile.

### ISSUE THREAD

**Issue by mjr4077au** [ZDoom/Raze#819] opened 2022-12-23 08:35 UTC
https://user-images.githubusercontent.com/48643140/209301943-3937e99e-009f-4141-83f8-8e2b9f40fada.mp4

**Comment by mjr4077au** [comment] 2023-01-03 23:38
For this particular issue, f4bc5d6df804a32dbe77b3b5a1f0083ae88923f7 is (obviously) where the issues start, but anything using `NAME_spawnsound` fails as `spawned->IntVar(NAME_spawnsound)` is always 0, therefore nothing to play.

@CandiceJoy has started to look at this and she believes that the issue lies with the $conreserve setup perhaps not being parsed correctly. She might have more info, but hopefully this helps with some direction.

**Comment by CandiceJoy** [comment] 2023-01-04 01:36
So this may apply to other SNDINFO calls too, but on Mac at the very least, what's going on is every time a $conreserve line is read, a new lump is created and a new element in S_sfx.  The issue is that no data gets associated with the lump, and the S_sfx element has no lump or data associated with it.  In fact, aside from a few non-crashing console errors, if I remove sndinfo.txt entirely, the game functions identically, sound included.

(Ignore resourceid, that gets set, correctly, later on)
<img width="488" alt="image" src="https://user-images.githubusercontent.com/8854890/210467425-cee0d0f0-b9b3-4ca0-b325-c798dad0fe11.png">

On the playing side, it comes into DukeActor_PlayActorSound as self,0,10,0 then to S_PlayActor_Sound then hits S_PlaySound3D where soundEngine->isValidSoundId(soundid) returns false, causing S_PlaySound3D to return -1 without a sound being played, which triggers the end of that line of vm execution.

**Comment by coelckers** [comment] 2023-01-04 19:06
You are right that $conreserve creates an empty sound - that's its entire purpose. It is there to ensure that sound name and sound ID get reliably connected so when CON reads the actual sound it gets placed into a proper slot that later can be referenced by name. The actual question is, why isn't it properly set up?

**Comment by coelckers** [comment] 2023-01-04 19:20
fixed in 220c1f0e7619df955ee2b7f8fabf76c26126ce25

The sound was fine, but the setup for the missile spawn incomplete with my changes elsewhere

**Closed by coelckers** 2023-01-04 19:20 UTC
Labels: bug
