### ISSUE TITLE
[BUG] Crazy crusher on DUKEDC4

### ISSUE THREAD

**Issue by Talon1024** [ZDoom/Raze#725] opened 2022-10-17 23:37 UTC
### Raze version

Raze master (db810250c3)

### Which game are you running with Raze?

Duke Nukem 3D

### What Operating System are you using?

Linux x86_64

### Please describe your specific OS version

Kubuntu 20.04.5

### Relevant hardware info

Intel i5-4690K CPU, NVidia GeForce GTX 970 GPU

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

On DUKEDC4 (Smithsonian Terror), there is a crusher that goes way too fast.

https://user-images.githubusercontent.com/6550500/196302757-88fc44a6-9a23-4dba-a05c-54afd65e467e.mp4

[Here's a saved game](https://github.com/ZDoom/Raze/files/9805165/save0001.zip).

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Start a new game on DUKEDC4
2. Go to the area where the crusher shown in the video is (I don't know what Raze's equivalent of `idmypos` or `warp` is)

**Comment by coelckers** [comment] 2022-10-18 05:11
This was already fixed in a later commit, but I transferred the fix to master because it may be a few days untl I get there.

**Closed by coelckers** 2022-10-18 05:11 UTC
Labels: bug

**Comment by Talon1024** [comment] 2022-11-04 01:41
Now the crushers are too slow. Here's a video taken on E2L4 from Duke Nukem 3D: Megaton Edition, showing the correct speed for the crusher:

https://user-images.githubusercontent.com/6550500/199866948-90da09b2-c963-405d-8805-7de31c7f55ef.mp4

**Comment by coelckers** [comment] 2022-11-05 13:27
Please do not report issues on closed bug tickets. Changes are that they'll never be looked at again.
I need a new ticket with all the usual info, like how to reproduce, a savegame that helps me get there quickly, and if not possible map coordinates.
