### ISSUE TITLE
[BUG] EXTREME MEMORY USAGE (up to 15GB!)

### ISSUE THREAD

**Issue by sylveonsylvia** [ZDoom/Raze#966] opened 2023-06-05 10:49 UTC
### Raze version

1.7.1

### Which game are you running with Raze?

Duke Nukem 3D

### What Operating System are you using?

Linux x86_64

### Please describe your specific OS version

arch linux

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

![image](https://github.com/ZDoom/Raze/assets/78629289/31b0f62b-c02b-45fb-be2f-c151af861a5d)

when launching the game never loads and runs in the background taking up a huge amount of memory 

### Steps to reproduce the behaviour.

Explain how to reproduce
1) launch the game

**Comment by anzix** [comment] 2023-06-18 21:15
As a temporary solution to the problem, I downloaded this version of the raze https://devbuilds.drdteam.org/raze-linux/raze-linux-x64-1.7pre-469-gcfef8c8a7.tar.xz. Which works without problems, tested on Shadow Warrior Classic (Steam)

**Comment by madame-rachelle** [comment] 2023-06-18 21:44
Not sure what the issue is and I don't use Linux dev tools often enough to know exactly how to diagnose this problem. @Blzut3 or @alexey-lysiuk may have some idea how to trace this down, if they have time to take a peek at this.

**Comment by madame-rachelle** [comment] 2023-06-18 21:45
By the way one thing that may help is to post your config files - never know, it may be config related. Please feel free to remove any personally identifying information (i.e. real name in any search paths, etc) if it exists.

**Comment by mjr4077au** [comment] 2023-06-18 22:44
If there's some memory issue that isn't occurring at head and only in the released version, I'm inclined to just close the issue. It'd be interesting to know whether Duke 3D works on that devbuild though because that's what the OP was playing.

We haven't discussed internally when 1.8 will ship but if the current state of master is working fine, I'd rather invest time bringing 1.8 out than a wild good chase trying to fix something obscure in 1 7.x.

**Comment by madame-rachelle** [comment] 2023-06-18 23:16
I'm inclined to agree, but, I'm also trying to rule out that this has anything to do with the way the binaries are being prepped. Knowing the cause of the issue might mitigate further issues into the future.

**Comment by Blzut3** [comment] 2023-06-19 02:21
Breaking GDB on the hang blames the radeonsi shader compiler.  Switching to Vulkan +vid_preferbackend 1 avoids the hang and memory usage is way down.

**Comment by Blzut3** [comment] 2023-06-19 02:30
Unrelated to this issue, but @madame-rachelle I would suggest static linking libjpeg since the ABI situation with libjpeg is a complete mess.  Debian and Ubuntu still differ here, although since the mess started Debian has reverted to the libjpeg62 ABI through libjpeg62-turbo and Ubuntu still provides libjpeg62.  Only Ubuntu has libjpeg8 now.  Otherwise your binaries look about right.

**Comment by michaelneverwins** [comment] 2023-06-26 01:38
> Switching to Vulkan +vid_preferbackend 1 avoids the hang and memory usage is way down.

Using "OpenGL ES" (`vid_preferbackend=2`) also avoids the memory issue for me, and might be a suitable workaround for those who can't use Vulkan.

**Comment by mjr4077au** [comment] 2023-09-24 05:03
Considering the problem is understood, our JPEG library has just been changed anyway, and 1.8 is not too far away, I'm closing this one for now. If the issue still occurs in the next released build, feel free to re-open the issue.

**Comment by Blzut3** [comment] 2023-09-24 05:11
I'm not sure if I'd say the problem is understood.  It's only been determined that it was an issue with the shader compilation on the radeonsi (at least) mesa driver.  Given other OpenGL drivers work, good chance it's a driver bug but I don't know enough to debug further than that.  I also don't know how much it matters if we're pushing Vulkan as the preferred code path anyway.

(And the jpeg thing had nothing to do with this issue, only mentioned here since Rachael's binaries were brought up.)

**Comment by mjr4077au** [comment] 2023-09-24 10:10
It appears I misunderstood RE: JPEG library etc, however as you've hinted, OpenGL will eventually be dropped and as it does appear to be a driver issue, it's not something we need to hold open. The author of this bug or #986 can raise it with the Mesa devs if they wish.

**Comment by Blzut3** [comment] 2023-09-24 19:47
Just for reference, I've confirmed this is still happening with the latest master (2916fe5) and Mesa 23.1.8 with radeonsi.  llvmpipe is not affected.  Raze 1.6.2 is not affected.  Vulkan (radv) and GLES are not affected.

**Comment by mjr4077au** [comment] 2023-09-25 12:20
@coelckers do you think I closed this one prematurely? Should we look at whatever shader changes have occurred that could be breaking this open source Radeon driver or leave it as a driver bug?

**Comment by Blzut3** [comment] 2023-09-26 02:03
Probably doesn't help narrowing things down, but again for reference: it looks like with the new 4.11.0 release GZDoom exhibits the same behavior.

**Comment by mjr4077au** [comment] 2023-09-26 02:17
If you've got the appropriate hardware, you can probably bisect it back to whatever change in the shader caused this. I just don't have the hardware to test this at all unfortunately.

**Comment by Blzut3** [comment] 2023-09-27 00:22
Bisecting raze points to b6da4ec.
Bisecting gzdoom points to https://github.com/ZDoom/gzdoom/commit/087050c2011cf53ab50e37335b93c37582521b2b

**Comment by d10sfan** [comment] 2023-09-27 04:18
As mentioned in the issue I created, I can replicate this on my system. Vulkan does work ok if I set  `+vid_preferbackend 1`, but since this defaults to opengl, can be a confusing experience for someone that isn't aware of this bug.

**Comment by mjr4077au** [comment] 2023-09-29 23:39
@Blzut3 I'm going to re-open this, I appreciate the bisection but is there any further profiling you can do to determine why this may be occurring for the driver?

**Comment by Blzut3** [comment] 2023-09-30 02:18
I know close to nothing about GPU programming and debugging so happy to try things but I don't have any intuition of what would be helpful.

Mesa 23.2 was just released.  Will be interesting to see if the bug happens to be fixed.  Just waiting for the Kisak PPA to update.  If it's still present I might open a ticket with Mesa.

**Comment by mjr4077au** [comment] 2023-09-30 02:21
Thanks mate, I definitely appreciate your help even after I erroneously closed off the ticket. Is just a crap situation as Graf or I don't have the appropriate hardware to test this ourselves.

**Comment by Blzut3** [comment] 2023-10-01 03:24
Mesa 23.2.1 appears to still be bugged.

**Comment by Blzut3** [comment] 2023-10-08 04:03
Reported to Mesa: https://gitlab.freedesktop.org/mesa/mesa/-/issues/9953

**Comment by Blzut3** [comment] 2023-11-03 00:59
https://gitlab.freedesktop.org/mesa/mesa/-/issues/9953#note_2152966

**Comment by Blzut3** [comment] 2023-11-16 03:32
Raze 1.8.1 is still affected.  No comment at all on the buffer sizes?

**Comment by coelckers** [comment] 2024-02-04 13:18
fixed in fe7738e9cc3238c9d635021d1ff25f28527a1b13

**Closed by coelckers** 2024-02-04 13:18 UTC
Labels: bug, OS-specific, tech issue

**Comment by Blzut3** [comment] 2024-02-06 00:26
Actual fix was 292c20842db1070376a90d134317a6bc720c5bad but confirmed working.
