### ISSUE TITLE
[BUG] Crash on Duke Caribbean Map04

### ISSUE THREAD

**Issue by AtifArshad1995** [ZDoom/Raze#628] opened 2022-01-20 10:06 UTC
### Raze version

1.3.1

### Which game are you running with Raze?

Duke Nukem 3D

### What Operating System are you using?

Windows 10

### Relevant hardware info

CPU = Intel i5-8250U, GPU = AMD Radeon 530, RAM = 4 GB

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

The crash happened when I dived into the smaller water pool at the start of the map04 of Duke Caribbean. Unfortunately, I have since not been able to reproduce this issue.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. 
2.
3.

### Provide a Log

[CrashReport.zip](https://github.com/coelckers/Raze/files/7904182/CrashReport.zip)
[raze.log](https://github.com/coelckers/Raze/files/7904187/raze.log)

**Comment by coelckers** [comment] 2022-01-22 09:15
I could not reproduce it either. This will have to wait until it can be reproduced reliable in a way that can be debugged.
There's also the chance, of course, that all the code changes since 1.3.1 have addressed this already.
In any case, put on hold until some more info becomes available.

**Comment by sinisterseed** [comment] 2022-01-22 18:46
I have not been able to reproduce it earlier either.

Do you remember if you did something unusual, or wholly ordinary the first time around, by any chance? For instance, we recently fixed a crash caused by shrinking enemies when the player got too close to them as they were still shrinking. 

Sometimes it's the things you least expect to cause issue, but of course, there's a good chance it may have been already fixed with the recent refactoring job. You can try the most recent devbuilds to see if that changes anything, your post implies you're still on the stable 1.3.1 release.

**Comment by AtifArshad1995** [comment] 2022-01-22 20:26
ent devbuilds to see if that changes anything, your post implies you're still on the stable 1.3.1 release.

**Comment by AtifArshad1995** [comment] 2022-01-22 20:28
Unfortunately, I didn't anything unusual and yes, I am using the stable 1.3.1. I have also not been able to reproduce the issue since then.

EDIT: Sorry about the closing/reopening.

**Closed** 2022-10-01 11:43 UTC
Labels: bug, on hold
