### ISSUE TITLE
[BUG] Drill on $dozer broken

### ISSUE THREAD

**Issue by Talon1024** [ZDoom/Raze#723] opened 2022-10-16 18:54 UTC
### Raze version

Raze master (b81a465336)

### Which game are you running with Raze?

Shadow Warrior

### What Operating System are you using?

Linux x86_64

### Please describe your specific OS version

Kubuntu 20.04.5 LTS

### Relevant hardware info

Intel i5-4690K CPU, NVidia GeForce GTX 970 GPU

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

The drill on $dozer.map is broken.

https://user-images.githubusercontent.com/6550500/196052739-5450f76d-aa27-49bf-bfe1-693c7df4df34.mp4

[Here's a saved game](https://github.com/ZDoom/Raze/files/9795454/save0005.zip)

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Play through $dozer.map (Zilla Construction)
2. Activate the drill at the end of the map, or walk under it
3. Walking under the drill teleports you to another dimension
4. Activating the drill does not work

**Comment by Talon1024** [comment] 2022-10-16 19:00
Tried with 3e3e3714dc, it works properly on that version.

**Comment by Talon1024** [comment] 2022-10-16 19:03
Actually, after saving my game and re-loading that saved game, this issue happened again, even on 3e3e3714dc.

**Comment by coelckers** [comment] 2022-10-16 19:25
Can you reproduce this from the 'refactoring5' branch as well?

**Comment by coelckers** [comment] 2022-10-16 20:16
The problem starts in commit 0b642dc631fe774c288330579cfaf4af9bd5c4d4 but I cannot see what's going wrong there.
It works completely fine from a fresh map start but as soon as the game it saved the whole thing stops working, suggesting some bad data in the savegame. But there's only one array that has changed and that looks like it is properly restored.

**Comment by coelckers** [comment] 2022-10-16 21:48
fixed in 31eb2e5f10f6a001719d1a26f0a597aa574dadff

**Closed by coelckers** 2022-10-16 21:48 UTC
Labels: bug
