### ISSUE TITLE
[99f1f09] [General] "CD Music Emulation" doesn't seem to work correctly

### ISSUE THREAD

**Issue by sinisterseed** [ZDoom/Raze#269] opened 2021-02-26 10:22 UTC
While trying to reproduce the SW music crash bug reported recently I ran into another discovery.

It seems this toggle doesn't really do its job. I just made a zip with the MIDI music from the Shareware and turned it off. Initially that seemed to work, as the intermission music and the intro theme was replaced, but once I started a game the CD music started playing once again.

Simply turning it off while leaving the music enabled also does nothing, it keeps playing the CD music anyway.

**Comment by coelckers** [comment] 2021-02-26 10:25
Please post your test file. I've been doing this for all eternity and never had a problem with it.

**Comment by sinisterseed** [comment] 2021-02-26 10:32
Here:

[swmus.zip](https://github.com/coelckers/Raze/files/6049032/swmus.zip)

**Comment by coelckers** [comment] 2021-02-26 12:42
Well, the song being played on the first level is just a MIDI version of the CD track. It sounds a little bit different, of course but is the same piece of music. For me it always works as intended - you may have to use something different as E1L01.MID for easier testing.

So sorry, unable to reproduce. When I disable CD emulation it will always pick the MIDI assigned to a map, provided it exists.

**Comment by coelckers** [comment] 2021-02-26 14:12
After further discussion this looks like a misunderstanding and everything is working as expected.

**Closed by coelckers** 2021-02-26 14:12 UTC
Labels: invalid
